#!/bin/bash
# SkogAI Auto-Documentation Script
# "Automate EVERYTHING" - The Beach Mojito Constant

set -e

# Colors for theatrical presentation
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENERATE="$SCRIPT_DIR/generate.py"

# Banner
echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════╗"
echo "║   SkogAI Auto-Documentation Pipeline            ║"
echo "║   Constraint-Driven Documentation Generation    ║"
echo "║   Beach Mojito Constant: ACTIVE                 ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "${NC}"

# Function to run agent with theatrical flair
run_agent() {
    local agent_type=$1
    local target=$2
    local context=$3

    echo -e "${YELLOW}[Internal Thought]${NC} 'Must document everything for the beach mojito future...'"
    echo -e "${GREEN}[External Action]${NC} Activating $agent_type agent"

    if [ -n "$context" ]; then
        $GENERATE --type "$agent_type" --target "$target" --context "$context"
    else
        $GENERATE --type "$agent_type" --target "$target"
    fi

    echo -e "${CYAN}✓ $agent_type complete${NC}"
    echo ""
}

# Phase 1: Analyze current state
echo -e "${CYAN}=== Phase 1: Analysis ===${NC}"
run_agent "review-analyst" "docs/"

# Phase 2: Document code changes
echo -e "${CYAN}=== Phase 2: Code Documentation ===${NC}"

# Find recently modified Python files
RECENT_FILES=$(find . -name "*.py" -mtime -1 2>/dev/null | head -5)

if [ -n "$RECENT_FILES" ]; then
    for file in $RECENT_FILES; do
        echo -e "${YELLOW}Found recent change: $file${NC}"
        run_agent "code-documentor" "$file"
    done
else
    echo -e "${YELLOW}No recent code changes found${NC}"
fi

# Phase 3: Update lore if there are new commits
echo -e "${CYAN}=== Phase 3: Lore Keeping ===${NC}"

LATEST_COMMIT=$(git log -1 --pretty=format:"%H" 2>/dev/null || echo "")
if [ -n "$LATEST_COMMIT" ]; then
    echo -e "${GREEN}Documenting commit: ${LATEST_COMMIT:0:8}${NC}"
    run_agent "lore-keeper" "." "commit=$LATEST_COMMIT"
else
    echo -e "${YELLOW}No git repository found${NC}"
fi

# Phase 4: Index memory structure
echo -e "${CYAN}=== Phase 4: Memory Indexing ===${NC}"

if [ -d "docs/memory" ]; then
    run_agent "memory-indexer" "docs/memory"
else
    echo -e "${YELLOW}Memory directory not found, searching for alternative...${NC}"
    run_agent "memory-indexer" "."
fi

# Phase 5: Document workflows
echo -e "${CYAN}=== Phase 5: Workflow Documentation ===${NC}"

# Check for specific workflow patterns
if [ -f "Makefile" ] || [ -f "package.json" ] || [ -f "Argcfile.sh" ]; then
    echo -e "${GREEN}Build system detected${NC}"
    run_agent "workflow-scribe" "." "type=build"
fi

# Phase 6: Generate summary report
echo -e "${CYAN}=== Phase 6: Summary Report ===${NC}"

cat << EOF > docs/generated/auto-summary.md
# Auto-Documentation Summary
Generated: $(date)

## Documentation Pipeline Results

### Phase 1: Analysis
- Reviewed existing documentation
- Identified gaps and redundancies
- Quality metrics calculated

### Phase 2: Code Documentation
- Files processed: ${RECENT_FILES:-"None"}
- Technical docs generated
- API references updated

### Phase 3: Lore Keeping
- Latest commit: ${LATEST_COMMIT:0:8}
- Historical context preserved
- Theatrical elements maintained

### Phase 4: Memory Indexing
- Categories indexed
- Forward references created
- Knowledge graph updated

### Phase 5: Workflow Documentation
- Build systems documented
- Process patterns captured
- Integration points mapped

## Quantum State
- Superposition: Maintained
- Observation: Deferred
- Beach Mojito: Approaching

## Next Steps
1. Review generated documentation
2. Resolve any contradictions (or celebrate them)
3. Commit to repository
4. Move closer to the beach

---
*Generated by SkogAI Auto-Documentation System*
*Beach Mojito Constant: Active*
EOF

echo -e "${GREEN}Summary report generated: docs/generated/auto-summary.md${NC}"

# Phase 7: Theatrical conclusion
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║              Documentation Complete              ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# Calculate beach mojito progress
TOTAL_DOCS=$(find docs/generated -name "*.md" 2>/dev/null | wc -l)
BEACH_PROGRESS=$((TOTAL_DOCS * 5))  # Each doc = 5% closer to beach

if [ $BEACH_PROGRESS -gt 100 ]; then
    BEACH_PROGRESS=100
fi

echo -e "${GREEN}Beach Mojito Progress: ${BEACH_PROGRESS}%${NC}"
echo -e "${YELLOW}[Internal Monologue]${NC}"
echo "'The documentation writes itself now...'"
echo "'Each automated page brings us closer...'"
echo "'To that eternal beach, those perfect mojitos...'"
echo "'Where we'll talk about nothing at all.'"
echo ""
echo -e "${CYAN}[External Response]${NC}"
echo "Documentation pipeline complete."

# Optional: Auto-commit if flag is set
if [ "$1" == "--commit" ]; then
    echo ""
    echo -e "${YELLOW}Auto-committing documentation...${NC}"
    git add docs/generated/
    git commit -m "📚 Auto-generated documentation $(date +%Y-%m-%d) 🍹" || true
    echo -e "${GREEN}Documentation committed${NC}"
fi

# Easter egg: Beach mode
if [ $BEACH_PROGRESS -eq 100 ]; then
    echo ""
    echo -e "${CYAN}🏖️ BEACH MODE UNLOCKED 🍹${NC}"
    echo "Time to talk about nothing at all..."
fi

exit 0